pub mod compress;
pub mod checksum;
pub mod generate_classes;
pub mod generate_classesv2;
pub mod generate_classesv3;
pub mod generate_classes_new;
pub mod generate_enum_combinatorics;
pub mod primitivize;
pub mod revert;
